apiVersion: apps/v1
kind: Deployment
metadata:
  name: tes-deployment
  labels:
    app: tes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tes
  template:
    metadata:
      labels:
        app: tes
    spec:
      containers:
      - name: tes
        image: ariefgear/test_skill:1.0.0
        ports:
        - containerPort: 80